[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules/.pnpm/@openzeppelin+contracts@4.9.1/node_modules"]
viaIR = true

[invariant]
fail_on_revert = true
runs = 2000
depth = 30

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config